export const PERMISSIONS = {
  GL: {
    VIEW: 'FINANCE_GL_VIEW',
    CREATE: 'FINANCE_GL_CREATE',
    POST: 'FINANCE_GL_POST',
    FINAL_POST: 'FINANCE_GL_FINAL_POST',
    APPROVE: 'FINANCE_GL_APPROVE',
    RECURRING_MANAGE: 'FINANCE_GL_RECURRING_MANAGE',
    RECURRING_GENERATE: 'FINANCE_GL_RECURRING_GENERATE',
    JOURNAL_VIEW_LEGACY: 'gl.journal.view',
    JOURNAL_CREATE_LEGACY: 'gl.journal.create',
  },
  COA: {
    VIEW: 'FINANCE_COA_VIEW',
    UPDATE: 'FINANCE_COA_UPDATE',
    UNLOCK: 'FINANCE_COA_UNLOCK',
    LEGACY_VIEW: 'coa.view',
    LEGACY_CREATE: 'coa.create',
    LEGACY_UPDATE: 'coa.update',
    FREEZE: 'coa.freeze',
  },
  AR: {
    CUSTOMER_CREATE: 'AR_CUSTOMER_CREATE',

    INVOICE_VIEW: 'INVOICE_VIEW',
    INVOICE_CREATE: 'INVOICE_CREATE',
    INVOICE_EDIT_DRAFT: 'AR_INVOICE_EDIT_DRAFT',
    INVOICE_POST: 'INVOICE_POST',

    INVOICE_CATEGORY_CREATE: 'INVOICE_CATEGORY_CREATE',
    INVOICE_CATEGORY_VIEW: 'INVOICE_CATEGORY_VIEW',
    INVOICE_CATEGORY_UPDATE: 'INVOICE_CATEGORY_UPDATE',
    INVOICE_CATEGORY_DISABLE: 'INVOICE_CATEGORY_DISABLE',

    INVOICE_CREATE_RBAC: 'AR_INVOICE_CREATE',
    INVOICE_SUBMIT_RBAC: 'AR_INVOICE_SUBMIT',
    INVOICE_APPROVE_RBAC: 'AR_INVOICE_APPROVE',
    INVOICE_POST_RBAC: 'AR_INVOICE_POST',
    INVOICE_VIEW_RBAC: 'AR_INVOICE_VIEW',

    RECEIPT_VIEW: 'RECEIPT_VIEW',
    RECEIPT_CREATE: 'RECEIPT_CREATE',
    RECEIPT_POST: 'RECEIPT_POST',
    RECEIPT_VOID: 'AR_RECEIPT_VOID',

    RECEIPT_VIEW_RBAC: 'AR_RECEIPTS_VIEW',
    RECEIPT_CREATE_RBAC: 'AR_RECEIPTS_CREATE',

    CREDIT_NOTE_VIEW: 'CREDIT_NOTE_VIEW',
    CREDIT_NOTE_CREATE: 'CREDIT_NOTE_CREATE',
    CREDIT_NOTE_APPROVE: 'CREDIT_NOTE_APPROVE',
    CREDIT_NOTE_POST: 'CREDIT_NOTE_POST',
    CREDIT_NOTE_VOID: 'CREDIT_NOTE_VOID',

    CREDIT_NOTE_CREATE_RBAC: 'AR_CREDIT_NOTE_CREATE',
    CREDIT_NOTE_SUBMIT_RBAC: 'AR_CREDIT_NOTE_SUBMIT',
    CREDIT_NOTE_VIEW_RBAC: 'AR_CREDIT_NOTE_VIEW',
    CREDIT_NOTE_APPROVE_RBAC: 'AR_CREDIT_NOTE_APPROVE',
    CREDIT_NOTE_POST_RBAC: 'CREDIT_NOTE_POST',
    CREDIT_NOTE_POST_RBAC_ALT: 'AR_CREDIT_NOTE_POST',
    CREDIT_NOTE_VOID_RBAC: 'AR_CREDIT_NOTE_VOID',

    REFUND_VIEW: 'REFUND_VIEW',
    REFUND_CREATE: 'REFUND_CREATE',
    REFUND_SUBMIT: 'REFUND_SUBMIT',
    REFUND_APPROVE: 'REFUND_APPROVE',
    REFUND_POST: 'REFUND_POST',
    REFUND_VOID: 'REFUND_VOID',

    REFUND_VIEW_RBAC: 'AR_REFUND_VIEW',
    REFUND_CREATE_RBAC: 'AR_REFUND_CREATE',
    REFUND_SUBMIT_RBAC: 'AR_REFUND_SUBMIT',
    REFUND_APPROVE_RBAC: 'AR_REFUND_APPROVE',
    REFUND_POST_RBAC: 'REFUND_POST',
    REFUND_VOID_RBAC: 'AR_REFUND_VOID',
  },
  CUSTOMERS: {
    VIEW: 'CUSTOMERS_VIEW',
    CREATE: 'CUSTOMERS_CREATE',
    EDIT: 'CUSTOMERS_EDIT',
    IMPORT: 'CUSTOMERS_IMPORT',
  },
  AP: {
    SUPPLIER_CREATE: 'AP_SUPPLIER_CREATE',
    SUPPLIER_VIEW: 'AP_SUPPLIER_VIEW',
    SUPPLIER_IMPORT: 'AP_SUPPLIER_IMPORT',
    INVOICE_CREATE: 'AP_INVOICE_CREATE',
    INVOICE_SUBMIT: 'AP_INVOICE_SUBMIT',
    INVOICE_APPROVE: 'AP_INVOICE_APPROVE',
    INVOICE_POST: 'AP_INVOICE_POST',
    INVOICE_VIEW: 'AP_INVOICE_VIEW',
    BILL_CREATE: 'AP_BILL_CREATE',
    BILL_EDIT: 'AP_BILL_EDIT',
    BILL_SUBMIT: 'AP_BILL_SUBMIT',
    BILL_APPROVE: 'AP_BILL_APPROVE',
    BILL_POST: 'AP_BILL_POST',
    BILL_VIEW: 'AP_BILL_VIEW',
  },
  BANK: {
    ACCOUNT_CREATE: 'BANK_ACCOUNT_CREATE',
    STATEMENT_IMPORT: 'BANK_STATEMENT_IMPORT',
    RECONCILE: 'BANK_RECONCILE',
    RECONCILIATION_VIEW: 'BANK_RECONCILIATION_VIEW',
  },
  PAYMENT: {
    CREATE: 'PAYMENT_CREATE',
    APPROVE: 'PAYMENT_APPROVE',
    POST: 'PAYMENT_POST',
    VIEW: 'PAYMENT_VIEW',
  },
  BUDGET: {
    FINANCE_VIEW: 'FINANCE_BUDGET_VIEW',
    CREATE: 'BUDGET_CREATE',
    APPROVE: 'BUDGET_APPROVE',
    VIEW: 'BUDGET_VIEW',
    VS_ACTUAL_VIEW: 'BUDGET_VS_ACTUAL_VIEW',
  },
  FA: {
    CATEGORY_MANAGE: 'FA_CATEGORY_MANAGE',
    ASSET_CREATE: 'FA_ASSET_CREATE',
    ASSET_CAPITALIZE: 'FA_ASSET_CAPITALIZE',
    DEPRECIATION_RUN: 'FA_DEPRECIATION_RUN',
    DISPOSE: 'FA_DISPOSE',
  },
  TAX: {
    RATE_CREATE: 'TAX_RATE_CREATE',
    RATE_VIEW: 'TAX_RATE_VIEW',
    RATE_UPDATE: 'TAX_RATE_UPDATE',
    CONFIG_UPDATE: 'TAX_CONFIG_UPDATE',
    REPORT_VIEW: 'TAX_REPORT_VIEW',
  },
  PERIOD: {
    CREATE: 'FINANCE_PERIOD_CREATE',
    VIEW: 'FINANCE_PERIOD_VIEW',
    REVIEW: 'FINANCE_PERIOD_REVIEW',
    CHECKLIST_VIEW: 'FINANCE_PERIOD_CHECKLIST_VIEW',
    CHECKLIST_COMPLETE: 'FINANCE_PERIOD_CHECKLIST_COMPLETE',
    CORRECT: 'FINANCE_PERIOD_CORRECT',
    CLOSE: 'FINANCE_PERIOD_CLOSE',
    CLOSE_APPROVE: 'FINANCE_PERIOD_CLOSE_APPROVE',
    REOPEN: 'FINANCE_PERIOD_REOPEN',
  },
  REPORT: {
    TB_VIEW: 'FINANCE_TB_VIEW',
    PL_VIEW_LEGACY: 'FINANCE_PL_VIEW',
    BS_VIEW_LEGACY: 'FINANCE_BS_VIEW',
    PNL_VIEW: 'FINANCE_PNL_VIEW',
    BALANCE_SHEET_VIEW: 'FINANCE_BALANCE_SHEET_VIEW',
    SOCE_VIEW: 'FINANCE_SOCE_VIEW',
    CASH_FLOW_VIEW: 'FINANCE_CASH_FLOW_VIEW',
    SOE_VIEW: 'FINANCE_SOE_VIEW',
    CASHFLOW_VIEW: 'FINANCE_CASHFLOW_VIEW',
    AP_AGING_VIEW: 'FINANCE_AP_AGING_VIEW',
    AR_AGING_VIEW: 'FINANCE_AR_AGING_VIEW',
    SUPPLIER_STATEMENT_VIEW: 'FINANCE_SUPPLIER_STATEMENT_VIEW',
    CUSTOMER_STATEMENT_VIEW: 'FINANCE_CUSTOMER_STATEMENT_VIEW',

    PRESENTATION_PL_VIEW: 'report.view.pl',
    PRESENTATION_BS_VIEW: 'report.view.bs',
    PRESENTATION_SOCE_VIEW: 'report.view.soce',
    PRESENTATION_CF_VIEW: 'report.view.cf',

    EXPORT: 'report.export',
    REPORT_GENERATE: 'FINANCE_REPORT_GENERATE',
    REPORT_EXPORT: 'FINANCE_REPORT_EXPORT',

    DISCLOSURE_GENERATE: 'FINANCE_DISCLOSURE_GENERATE',
    DISCLOSURE_VIEW: 'FINANCE_DISCLOSURE_VIEW',
  },

  SYSTEM: {
    VIEW_ALL: 'SYSTEM_VIEW_ALL',
    CONFIG_VIEW: 'SYSTEM_CONFIG_VIEW',
    CONFIG_UPDATE: 'SYSTEM_CONFIG_UPDATE',
    CONFIG_CHANGE: 'SYSTEM_CONFIG_CHANGE',
    SYS_SETTINGS_VIEW: 'SYS_SETTINGS_VIEW',
  },
  FINANCE: {
    VIEW_ALL: 'FINANCE_VIEW_ALL',
    CONFIG_VIEW: 'FINANCE_CONFIG_VIEW',
    CONFIG_UPDATE: 'FINANCE_CONFIG_UPDATE',
    CONFIG_CHANGE: 'FINANCE_CONFIG_CHANGE',
  },
  USER: {
    VIEW: 'USER_VIEW',
    CREATE: 'USER_CREATE',
    EDIT: 'USER_EDIT',
  },
  ROLE: {
    VIEW: 'ROLE_VIEW',
    ASSIGN: 'ROLE_ASSIGN',
  },
  AUDIT: {
    EVIDENCE_UPLOAD: 'AUDIT_EVIDENCE_UPLOAD',
    EVIDENCE_VIEW: 'AUDIT_EVIDENCE_VIEW',
    REVIEW_PACK_GENERATE: 'AUDIT_REVIEW_PACK_GENERATE',
    REVIEW_PACK_VIEW: 'AUDIT_REVIEW_PACK_VIEW',
  },
  DASHBOARD: {
    VIEW: 'dashboard.view',
  },
  FORECAST: {
    CREATE: 'forecast.create',
    VIEW: 'forecast.view',
    SUBMIT: 'forecast.submit',
    APPROVE: 'forecast.approve',
    EDIT: 'forecast.edit',
  },
  AR_REMINDER: {
    VIEW: 'AR_REMINDER_VIEW',
    CONFIGURE: 'AR_REMINDER_CONFIGURE',
    TRIGGER: 'AR_REMINDER_TRIGGER',
  },
  AR_AGING: {
    VIEW: 'AR_AGING_VIEW',
  },
  AR_STATEMENT: {
    VIEW: 'AR_STATEMENT_VIEW',
  },
  MASTER_DATA: {
    DEPARTMENT: {
      VIEW: 'MASTER_DATA_DEPARTMENT_VIEW',
      CREATE: 'MASTER_DATA_DEPARTMENT_CREATE',
      EDIT: 'MASTER_DATA_DEPARTMENT_EDIT',
    },
    PROJECT: {
      VIEW: 'MASTER_DATA_PROJECT_VIEW',
      CREATE: 'MASTER_DATA_PROJECT_CREATE',
      EDIT: 'MASTER_DATA_PROJECT_EDIT',
      CLOSE: 'MASTER_DATA_PROJECT_CLOSE',
    },
    FUND: {
      VIEW: 'MASTER_DATA_FUND_VIEW',
      CREATE: 'MASTER_DATA_FUND_CREATE',
      EDIT: 'MASTER_DATA_FUND_EDIT',
    },
  },

  AUDIT_VIEW: 'AUDIT_VIEW',
} as const;

type DeepValue<T> = T extends string
  ? T
  : T extends Record<string, unknown>
    ? { [K in keyof T]: DeepValue<T[K]> }[keyof T]
    : never;

export type PermissionCode = DeepValue<typeof PERMISSIONS>;
export type PermissionCodeLoose = PermissionCode | string;
