import { useEffect, useMemo, useState } from 'react';
import type { ApiError } from '../services/api';
import { downloadReviewPack, generateReviewPack, listReviewPacks, type ReviewPackRow } from '../services/reviewPacks';
import { useAuth } from '../auth/AuthContext';
import { Card } from './Card';
import { Button } from './Button';
import { Alert } from './Alert';
import { DataTable } from './DataTable';

export function ReviewPackPanel(props: { periodId: string }) {
  const { hasPermission } = useAuth();
  const canView = hasPermission('AUDIT_REVIEW_PACK_VIEW');
  const canGenerate = hasPermission('AUDIT_REVIEW_PACK_GENERATE');

  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<any>(null);
  const [rows, setRows] = useState<ReviewPackRow[]>([]);

  const errBody = (error as ApiError | any)?.body;

  const lockedReason = useMemo(() => {
    if (!canGenerate) return 'Missing permission: AUDIT_REVIEW_PACK_GENERATE';
    return null;
  }, [canGenerate]);

  async function load() {
    if (!canView) return;
    if (!props.periodId) return;

    setLoading(true);
    setError(null);
    try {
      const resp = await listReviewPacks(props.periodId);
      setRows(resp);
    } catch (e) {
      setError(e);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.periodId, canView]);

  async function onGenerate() {
    if (!canGenerate) return;
    setGenerating(true);
    setError(null);
    try {
      await generateReviewPack(props.periodId);
      await load();
    } catch (e) {
      setError(e);
    } finally {
      setGenerating(false);
    }
  }

  async function onDownload(packId: string) {
    if (!canView) return;
    setError(null);
    try {
      const out = await downloadReviewPack(props.periodId, packId);
      const url = URL.createObjectURL(out.blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = out.fileName;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError(e);
    }
  }

  return (
    <Card
      title="Management & Audit Review Pack"
      subtitle="Generate and download period review packs."
      actions={
        <Button onClick={load} disabled={loading || !canView} variant="secondary" size="sm">
          {loading ? 'Loading…' : 'Reload'}
        </Button>
      }
      style={{ marginTop: 16 }}
    >

      {!canView ? (
        <div style={{ marginTop: 12 }}>
          <Alert tone="info" title="No access">You do not have permission to view review packs.</Alert>
        </div>
      ) : null}

      {canView ? (
        <div style={{ marginTop: 8, display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
          <Button onClick={onGenerate} disabled={!canGenerate || generating} title={lockedReason ?? undefined} variant="accent">
            {generating ? 'Generating…' : 'Generate Review Pack'}
          </Button>
          {!canGenerate ? <span style={{ fontSize: 12, color: '#666' }}>{lockedReason}</span> : null}
        </div>
      ) : null}

      {error ? (
        <div style={{ marginTop: 12 }}>
          <Alert tone="error" title="Review pack error">
            <pre style={{ margin: 0, whiteSpace: 'pre-wrap', fontSize: 12 }}>{JSON.stringify(errBody ?? error, null, 2)}</pre>
          </Alert>
        </div>
      ) : null}

      {canView ? (
        <div style={{ marginTop: 12 }}>
          <DataTable>
            <DataTable.Head sticky>
              <tr>
                <DataTable.Th>Generated At</DataTable.Th>
                <DataTable.Th>Generated By</DataTable.Th>
                <DataTable.Th>Size</DataTable.Th>
                <DataTable.Th align="right">Action</DataTable.Th>
              </tr>
            </DataTable.Head>
            <DataTable.Body>
              {rows.length === 0 ? <DataTable.Empty colSpan={4} title="No review packs generated yet." /> : null}
              {rows.map((r, idx) => (
                <DataTable.Row key={r.id} zebra index={idx}>
                  <DataTable.Td>{r.createdAt}</DataTable.Td>
                  <DataTable.Td>{r.generatedBy?.email ?? '-'}</DataTable.Td>
                  <DataTable.Td>{r.zipSize}</DataTable.Td>
                  <DataTable.Td align="right">
                    <Button onClick={() => onDownload(r.id)} disabled={!canView} variant="secondary" size="sm">
                      Download
                    </Button>
                  </DataTable.Td>
                </DataTable.Row>
              ))}
            </DataTable.Body>
          </DataTable>
        </div>
      ) : null}
    </Card>
  );
}
