-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "allowSelfPosting" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "receiptBankName" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "receiptBankAccountName" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "receiptBankAccountNumber" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "receiptBankBranch" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "receiptBankSwiftCode" TEXT;
