ALTER TYPE "AuditEventType" ADD VALUE 'GL_JOURNAL_SYSTEM_REVIEWED';
ALTER TYPE "AuditEventType" ADD VALUE 'GL_LIFECYCLE_BYPASS_BLOCKED';

CREATE TYPE "JournalReviewMode" AS ENUM ('MANUAL_REVIEW', 'SYSTEM_REVIEW', 'OVERRIDE_REVIEW');

ALTER TABLE "JournalEntry" ADD COLUMN "reviewMode" "JournalReviewMode";
