-- AlterEnum
BEGIN;
CREATE TYPE "AuditEventType_new" AS ENUM ('JOURNAL_POST', 'PERIOD_CHECKLIST_COMPLETE', 'PERIOD_CLOSE', 'PERIOD_REOPEN', 'AP_POST', 'AR_POST', 'INVOICE_POSTED', 'INVOICE_DRAFT_CREATED', 'INVOICE_DRAFT_EDITED', 'FA_CAPITALIZE', 'FA_DEPRECIATION_RUN', 'FA_DISPOSE', 'BANK_RECONCILIATION_MATCH', 'CREATE_BANK_STATEMENT', 'ADD_BANK_STATEMENT_LINE', 'BANK_RECON_LINE_MATCHED', 'BANK_RECON_LINE_UNMATCHED', 'BANK_RECON_ADJUSTMENT_JOURNAL_CREATED', 'EVIDENCE_UPLOAD', 'BUDGET_CREATE', 'BUDGET_APPROVE', 'REPORT_VIEW', 'REPORT_EXPORT', 'FORECAST_CREATE', 'FORECAST_UPDATE', 'FORECAST_SUBMIT', 'FORECAST_APPROVE', 'FORECAST_SUPERSEDE', 'FORECAST_VIEW', 'DASHBOARD_VIEW', 'ORGANISATION_UPDATE', 'ORGANISATION_LOGO_UPLOAD', 'USER_CREATE', 'USER_STATUS_CHANGE', 'USER_ROLE_ASSIGN', 'COA_CREATE', 'COA_UPDATE', 'COA_DEACTIVATE', 'COA_FREEZE', 'COA_UNFREEZE', 'COA_HIERARCHY_CHANGE', 'COA_LOCKED', 'COA_UNLOCKED', 'JOURNAL_CREATE', 'JOURNAL_UPDATE', 'JOURNAL_PARK', 'JOURNAL_REVERSE', 'RECURRING_TEMPLATE_CREATE', 'RECURRING_TEMPLATE_UPDATE', 'RECURRING_JOURNAL_GENERATED', 'JOURNAL_UPLOAD', 'JOURNAL_UPLOAD_FAILED', 'DISCLOSURE_NOTE_GENERATE', 'DISCLOSURE_NOTE_VIEW', 'GL_JOURNAL_SUBMITTED', 'GL_JOURNAL_REVIEWED', 'GL_JOURNAL_POSTED', 'GL_JOURNAL_REVERSED', 'GL_JOURNAL_POST_BLOCKED', 'FA_POST', 'GL_JOURNAL_REJECTED', 'GL_JOURNAL_RETURNED_BY_POSTER', 'GL_JOURNAL_REVERSAL_INITIATED', 'GL_JOURNAL_REVERSAL_APPROVED', 'GL_JOURNAL_REVERSAL_POSTED', 'GL_JOURNAL_REVERSAL_ASSIGNED', 'GL_JOURNAL_RISK_COMPUTED', 'GL_JOURNAL_BUDGET_EVALUATED', 'COA_IMPORTED', 'COA_CLEANUP_EXECUTED', 'PERIOD_CREATED', 'PERIOD_REOPENED', 'PERIOD_CLOSED', 'DEPARTMENT_CREATED', 'DEPARTMENT_UPDATED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_CLOSED', 'FUND_CREATED', 'FUND_UPDATED', 'INVOICE_CATEGORY_CREATED', 'INVOICE_CATEGORY_UPDATED', 'INVOICE_CATEGORY_STATUS_CHANGE', 'TAX_RATE_CREATED', 'TAX_RATE_UPDATED', 'TAX_RATE_STATUS_CHANGE', 'TAX_CONFIG_UPDATED', 'PERIOD_CORRECTION', 'PERIOD_CORRECTED', 'AR_REMINDER_SENT', 'AR_REMINDER_CONFIG_CHANGED', 'PAYMENT_PROPOSAL_CREATED', 'PAYMENT_PROPOSAL_SUBMITTED', 'PAYMENT_PROPOSAL_APPROVED', 'PAYMENT_PROPOSAL_REJECTED', 'PAYMENT_RUN_CREATED', 'PAYMENT_RUN_EXECUTED', 'BILL_REJECTED', 'IMPREST_TYPE_POLICY_CREATED', 'IMPREST_TYPE_POLICY_UPDATED', 'IMPREST_TYPE_POLICY_STATUS_CHANGE', 'IMPREST_FACILITY_CREATED', 'IMPREST_FACILITY_UPDATED', 'IMPREST_FACILITY_STATUS_CHANGE', 'IMPREST_CASE_CREATED', 'IMPREST_CASE_SUBMITTED', 'IMPREST_CASE_REVIEWED', 'IMPREST_CASE_APPROVED', 'IMPREST_CASE_REJECTED', 'IMPREST_CASE_EVIDENCE_LINKED', 'IMPREST_CASE_ISSUED', 'IMPREST_CASE_SETTLED');
ALTER TABLE "AuditEvent" ALTER COLUMN "eventType" TYPE "AuditEventType_new" USING ("eventType"::text::"AuditEventType_new");
ALTER TYPE "AuditEventType" RENAME TO "AuditEventType_old";
ALTER TYPE "AuditEventType_new" RENAME TO "AuditEventType";
DROP TYPE "public"."AuditEventType_old";
COMMIT;

-- AlterTable
ALTER TABLE "BankStatementLine" ADD COLUMN     "adjustmentJournalId" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "BankStatementLine_adjustmentJournalId_key" ON "BankStatementLine"("adjustmentJournalId");

-- AddForeignKey
ALTER TABLE "BankStatementLine" ADD CONSTRAINT "BankStatementLine_adjustmentJournalId_fkey" FOREIGN KEY ("adjustmentJournalId") REFERENCES "JournalEntry"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

