export const FINANCE_PERMISSIONS = {
  GL: {
    VIEW: 'FINANCE_GL_VIEW',
    CREATE: 'FINANCE_GL_CREATE',
    POST: 'FINANCE_GL_POST',
    FINAL_POST: 'FINANCE_GL_FINAL_POST',
    APPROVE: 'FINANCE_GL_APPROVE',
    RECURRING_MANAGE: 'FINANCE_GL_RECURRING_MANAGE',
    RECURRING_GENERATE: 'FINANCE_GL_RECURRING_GENERATE',
  },
  COA: {
    VIEW: 'FINANCE_COA_VIEW',
    UPDATE: 'FINANCE_COA_UPDATE',
    UNLOCK: 'FINANCE_COA_UNLOCK',
    LEGACY_VIEW: 'coa.view',
    LEGACY_CREATE: 'coa.create',
    LEGACY_UPDATE: 'coa.update',
    FREEZE: 'coa.freeze',
  },
  AR: {
    CUSTOMER_CREATE: 'AR_CUSTOMER_CREATE',
    INVOICE_CREATE: 'AR_INVOICE_CREATE',
    INVOICE_SUBMIT: 'AR_INVOICE_SUBMIT',
    INVOICE_APPROVE: 'AR_INVOICE_APPROVE',
    INVOICE_POST: 'AR_INVOICE_POST',
    INVOICE_VIEW: 'AR_INVOICE_VIEW',
    RECEIPT_READ: 'AR_RECEIPT_READ',
    RECEIPT_CREATE: 'AR_RECEIPT_CREATE',
    RECEIPT_VOID: 'AR_RECEIPT_VOID',
  },
  AP: {
    SUPPLIER_CREATE: 'AP_SUPPLIER_CREATE',
    INVOICE_CREATE: 'AP_INVOICE_CREATE',
    INVOICE_SUBMIT: 'AP_INVOICE_SUBMIT',
    INVOICE_APPROVE: 'AP_INVOICE_APPROVE',
    INVOICE_POST: 'AP_INVOICE_POST',
    INVOICE_VIEW: 'AP_INVOICE_VIEW',
  },
  BANK: {
    ACCOUNT_CREATE: 'BANK_ACCOUNT_CREATE',
    STATEMENT_IMPORT: 'BANK_STATEMENT_IMPORT',
    RECONCILE: 'BANK_RECONCILE',
    RECONCILIATION_VIEW: 'BANK_RECONCILIATION_VIEW',
  },
  PAYMENT: {
    CREATE: 'PAYMENT_CREATE',
    APPROVE: 'PAYMENT_APPROVE',
    POST: 'PAYMENT_POST',
    VIEW: 'PAYMENT_VIEW',
  },
  BUDGET: {
    FINANCE_VIEW: 'FINANCE_BUDGET_VIEW',
    CREATE: 'BUDGET_CREATE',
    APPROVE: 'BUDGET_APPROVE',
    VIEW: 'BUDGET_VIEW',
    VS_ACTUAL_VIEW: 'BUDGET_VS_ACTUAL_VIEW',
  },
  FA: {
    CATEGORY_MANAGE: 'FA_CATEGORY_MANAGE',
    ASSET_CREATE: 'FA_ASSET_CREATE',
    ASSET_CAPITALIZE: 'FA_ASSET_CAPITALIZE',
    DEPRECIATION_RUN: 'FA_DEPRECIATION_RUN',
    DISPOSE: 'FA_DISPOSE',
  },
  TAX: {
    RATE_CREATE: 'TAX_RATE_CREATE',
    RATE_VIEW: 'TAX_RATE_VIEW',
    REPORT_VIEW: 'TAX_REPORT_VIEW',
  },
  PERIOD: {
    CREATE: 'FINANCE_PERIOD_CREATE',
    VIEW: 'FINANCE_PERIOD_VIEW',
    REVIEW: 'FINANCE_PERIOD_REVIEW',
    CHECKLIST_COMPLETE: 'FINANCE_PERIOD_CHECKLIST_COMPLETE',
    CLOSE: 'FINANCE_PERIOD_CLOSE',
    CLOSE_APPROVE: 'FINANCE_PERIOD_CLOSE_APPROVE',
    REOPEN: 'FINANCE_PERIOD_REOPEN',
  },
  REPORT: {
    TB_VIEW: 'FINANCE_TB_VIEW',
    PL_VIEW_LEGACY: 'FINANCE_PL_VIEW',
    BS_VIEW_LEGACY: 'FINANCE_BS_VIEW',
    PNL_VIEW: 'FINANCE_PNL_VIEW',
    BALANCE_SHEET_VIEW: 'FINANCE_BALANCE_SHEET_VIEW',
    SOCE_VIEW: 'FINANCE_SOCE_VIEW',
    CASH_FLOW_VIEW: 'FINANCE_CASH_FLOW_VIEW',
    SOE_VIEW: 'FINANCE_SOE_VIEW',
    CASHFLOW_VIEW: 'FINANCE_CASHFLOW_VIEW',
    AP_AGING_VIEW: 'FINANCE_AP_AGING_VIEW',
    AR_AGING_VIEW: 'FINANCE_AR_AGING_VIEW',
    SUPPLIER_STATEMENT_VIEW: 'FINANCE_SUPPLIER_STATEMENT_VIEW',
    CUSTOMER_STATEMENT_VIEW: 'FINANCE_CUSTOMER_STATEMENT_VIEW',

    PRESENTATION_PL_VIEW: 'report.view.pl',
    PRESENTATION_BS_VIEW: 'report.view.bs',
    PRESENTATION_SOCE_VIEW: 'report.view.soce',
    PRESENTATION_CF_VIEW: 'report.view.cf',

    EXPORT: 'report.export',
    REPORT_GENERATE: 'FINANCE_REPORT_GENERATE',
    REPORT_EXPORT: 'FINANCE_REPORT_EXPORT',

    DISCLOSURE_GENERATE: 'FINANCE_DISCLOSURE_GENERATE',
    DISCLOSURE_VIEW: 'FINANCE_DISCLOSURE_VIEW',
  },
} as const;

type FinancePermissionModuleKey = keyof typeof FINANCE_PERMISSIONS;

type FinancePermissionValueUnion = {
  [K in FinancePermissionModuleKey]: (typeof FINANCE_PERMISSIONS)[K][keyof (typeof FINANCE_PERMISSIONS)[K]];
}[FinancePermissionModuleKey];

export type FinancePermissionCode = FinancePermissionValueUnion | string;
