export const PERMISSIONS = {
  BUDGET: {
    VIEW: "BUDGET_VIEW",
    CREATE: "BUDGET_CREATE",
    APPROVE: "BUDGET_APPROVE",
    VS_ACTUAL_VIEW: "BUDGET_VS_ACTUAL_VIEW",
  },
  GL: {
    VIEW: "FINANCE_GL_VIEW",
  },
  FINANCE: {
    BUDGET_VIEW: "FINANCE_BUDGET_VIEW",
    VIEW_ALL: "FINANCE_VIEW_ALL",
  },
  SYSTEM: {
    VIEW_ALL: "SYSTEM_VIEW_ALL",
  },
  AR: {
    CUSTOMER: {
      CREATE: "AR_CUSTOMER_CREATE",
    },
    CUSTOMERS: {
      VIEW: "CUSTOMERS_VIEW",
      CREATE: "CUSTOMERS_CREATE",
      EDIT: "CUSTOMERS_EDIT",
      IMPORT: "CUSTOMERS_IMPORT",
    },
    AGING: {
      VIEW: "AR_AGING_VIEW",
    },
    STATEMENT: {
      VIEW: "AR_STATEMENT_VIEW",
    },
    REMINDER: {
      VIEW: "AR_REMINDER_VIEW",
      CONFIGURE: "AR_REMINDER_CONFIGURE",
      TRIGGER: "AR_REMINDER_TRIGGER",
    },
    INVOICE: {
      VIEW: "INVOICE_VIEW",
      CREATE: "INVOICE_CREATE",
      EDIT_DRAFT: "AR_INVOICE_EDIT_DRAFT",
      POST: "INVOICE_POST",
    },
    RECEIPT: {
      VIEW: "RECEIPT_VIEW",
      CREATE: "RECEIPT_CREATE",
      POST: "RECEIPT_POST",
      VOID: "AR_RECEIPT_VOID",
    },
    CREDIT_NOTE: {
      VIEW: "CREDIT_NOTE_VIEW",
      CREATE: "CREDIT_NOTE_CREATE",
      SUBMIT: "AR_CREDIT_NOTE_SUBMIT",
      APPROVE: "CREDIT_NOTE_APPROVE",
      POST: "CREDIT_NOTE_POST",
      VOID: "CREDIT_NOTE_VOID",
    },
    REFUND: {
      VIEW: "REFUND_VIEW",
      CREATE: "REFUND_CREATE",
      SUBMIT: "REFUND_SUBMIT",
      APPROVE: "REFUND_APPROVE",
      POST: "REFUND_POST",
      VOID: "REFUND_VOID",
    },
  },
  AP: {
    SUPPLIER: {
      CREATE: "AP_SUPPLIER_CREATE",
      VIEW: "AP_SUPPLIER_VIEW",
      IMPORT: "AP_SUPPLIER_IMPORT",
    },
    STATEMENT_EXPORT: "AP_STATEMENT_EXPORT",
    INVOICE_EXPORT: "AP_INVOICE_EXPORT",
    PAYMENT_PROPOSAL: {
      VIEW: "AP_PAYMENT_PROPOSAL_VIEW",
      CREATE: "AP_PAYMENT_PROPOSAL_CREATE",
      SUBMIT: "AP_PAYMENT_PROPOSAL_SUBMIT",
      APPROVE: "AP_PAYMENT_PROPOSAL_APPROVE",
    },
    INVOICE: {
      VIEW: "AP_INVOICE_VIEW",
      CREATE: "AP_INVOICE_CREATE",
      SUBMIT: "AP_INVOICE_SUBMIT",
      APPROVE: "AP_INVOICE_APPROVE",
      POST: "AP_INVOICE_POST",
    },
    PAYMENT: {
      CREATE: "PAYMENT_CREATE",
      APPROVE: "PAYMENT_APPROVE",
      POST: "PAYMENT_POST",
      VIEW: "PAYMENT_VIEW",
    },
  },
  BANK: {
    ACCOUNT: {
      CREATE: "BANK_ACCOUNT_CREATE",
    },
    STATEMENT: {
      IMPORT: "BANK_STATEMENT_IMPORT",
    },
    RECONCILIATION: {
      VIEW: "BANK_RECONCILIATION_VIEW",
      MATCH: "BANK_RECONCILE",
    },
  },
  REPORT: {
    VIEW: {
      TRIAL_BALANCE: "FINANCE_TB_VIEW",
      PROFIT_LOSS: "report.view.pl",
      BALANCE_SHEET: "report.view.bs",
      CASH_FLOW: "FINANCE_CASHFLOW_VIEW",
      SOCE: "FINANCE_SOE_VIEW",
      AP_AGING: "FINANCE_AP_AGING_VIEW",
      AR_AGING: "FINANCE_AR_AGING_VIEW",
      SUPPLIER_STATEMENT: "FINANCE_SUPPLIER_STATEMENT_VIEW",
      CUSTOMER_STATEMENT: "FINANCE_CUSTOMER_STATEMENT_VIEW",
      VAT_SUMMARY: "TAX_REPORT_VIEW",
      BUDGET_VS_ACTUAL: "BUDGET_VS_ACTUAL_VIEW",
    },
    GENERATE: "FINANCE_REPORT_GENERATE",
    EXPORT: "FINANCE_REPORT_EXPORT",
  },
  DISCLOSURE: {
    VIEW: "FINANCE_DISCLOSURE_VIEW",
    GENERATE: "FINANCE_DISCLOSURE_GENERATE",
  },
  PAYMENT: {
    VIEW: "PAYMENT_VIEW",
    CREATE: "PAYMENT_CREATE",
    APPROVE: "PAYMENT_APPROVE",
    POST: "PAYMENT_POST",
  },
} as const;
